### ISSUE TITLE
Invoking for 960x540 resolution

### ISSUE THREAD

**Issue by clort81** [ValHaris/asc-hq#1]
Hi!  Trying to run on maemo-leste for droid4.

user@ml1:~$ asc -w -x 940 -y 520

parameter range error: y must be >= 480

520 is greater than 480

Any invocation with -w breaks, but fullscreen is working, sort of.

I will try to get this into the library of working games.  Cheers!

**Comment by ValHaris** [comment]
A long time ago, the minimum resolution of ASC was changed from 640*480 to 800*600. But apparently, the error messages were never updated. I just did that.

Most functions of ASC may run with a little less height, the main display and cargo dialog seem to have some headroom. But some more exotic dialogs have a height of 600 pixels and may not be shown completely when running with less.

If you want, you can play around a little bit with the minimum value. It's defined at source/clparser/asc.cpp:79
